### ISSUE TITLE
Unhanded exception: closed stream in HTTP::Server

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1077]
Running a wrk test against a basic HTTP::Server instance regularly raises an `IO::Error.new("closed stream")` exception when the connection closes (at least on my Ubuntu 14.04 64bits laptop). For example:

```crystal
require "http/server"

HTTP::Server.new(9292) do |request|
  HTTP::Response.ok("text/plain", "OK")
end
```
```
$ wrk -d 1 http://localhost:9292/
```

**Comment by Sdogruyol** [comment]
Hey @ysbaddaden, what's your version of wrk? Currently i'm writing a http client for Crystal and using wrk as a comparison and never had a problem with it. I'm using wrk 4.0.0 on OS X 10.10

**Comment by ysbaddaden** [comment]
I'm using wrk 4.0.0 on linux / 64bits. It happens all the time, even with 10 concurrent connections, or when killing wrk.

**Comment by ysbaddaden** [comment]
The exception comes from here: https://github.com/manastech/crystal/blob/fa209500d720e37ea9e41a2a6fdad2e3a793beb2/src/io/file_descriptor_io.cr#L138 and happens because we're trying to close an unbuffered IO twice.

**Comment by waj** [comment]
There was a workaround for #171 but that issue is already fixed. I removed the hack and now it should close once per socket.

**Comment by ysbaddaden** [comment]
Yup, this is fixed. Thanks!

**Comment by nopc0de** [comment]
This problem (or a version of it) still occurs for me using the latest version of crystal and the default curl binary on OSX 10.10.4 (Yosemite, latest stable OSX)

Debug/verbose output here: https://gist.github.com/nopc0de/e2072de8716b5539a160

**Comment by asterite** [comment]
@nopc0de I can't reproduce this, but maybe there's another problem.

Are you compiling the program using the standard library in HEAD and doing `bin/crystal` (instead of just `crystal`)?

**Comment by nopc0de** [comment]
@asterite Yes. I downloaded 0.7.5 with homebrew, then compiled the master branch from source and then uninstalled 0.7.5 with brew. (& Moved the .build/crystal binary to a dir in my $PATH)

    ⊨ crystal -v                                                                      ~
    Crystal 0.7.5 [4288b21] (Fri Aug  7 22:11:15 UTC 2015)

**Comment by jhass** [comment]
Hum, that shouldn't have found any stdlib at all. Try making source to use the `bin/crystal` script in the repository (and that it says `Using .build/crystal`). You can reference it by fullpath from anywhere.

**Comment by nopc0de** [comment]
@jhass I pulled the latest changes and recompiled crystal (compiler).

    ⊨ ../../../../src_apps/crystal/bin/crystal -v                    
    Using compiled compiler at .build/crystal
    Crystal 0.7.5 [bc679fa] (Sun Aug  9 14:33:10 UTC 2015)
    ⊨ ../../../../src_apps/crystal/bin/crystal run app.cr       
    Using compiled compiler at .build/crystal

Then:

    ⊨ curl localhost:8080
    curl: (52) Empty reply from server

I'm no longer getting that exception from crystal though, so I guess thats progress.

**Comment by jhass** [comment]
let's be sure, what's `cat app.cr`?

**Comment by nopc0de** [comment]
https://gist.github.com/nopc0de/e2072de8716b5539a160

**Comment by jhass** [comment]
Alright, looks like @nopc0de curl sends an empty `Referer` header by default, you can reproduce with newer curls using `curl -e "" http://localhost:8080`

**Comment by codenoid** [comment]
pwiz help me > https://github.com/crystal-lang/crystal-db/issues/58

**Comment by RX14** [comment]
@codenoid Please do not bump long-dead unrelated issues with a plea for help. It's rude and makes it less likely for someone to want to help you. Your crystal-db issue has only been open for 2 hours, please be patient.
